name: Release to PyPi

on:
  release:
    types: [published]

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    environment: release  # configured in repo Settings/Environments; referenced in PyPI OIDC
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: "2.0.1"
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: |
        poetry self add "poetry-dynamic-versioning[plugin]"
    - name: Build package with poetry
      run: |
        poetry build -f wheel
        poetry build -f sdist
    - name: Publish to PyPI with pypi-publish (trusted publishing)
      uses: pypa/gh-action-pypi-publish@v1.8.14

